# Generated by Django 2.2.4 on 2019-09-29 17:05

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=simditor.fields.RichTextField(verbose_name='评论正文'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='reply_content',
            field=simditor.fields.RichTextField(verbose_name='正文'),
        ),
    ]
